export const exportSummaryToPDF = (summaryText: string, documentTitle: string, originalContent: string) => {
  // Create a new window for printing
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    alert('Please allow popups to generate PDF');
    return;
  }

  // Create the HTML content for the PDF
  const htmlContent = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>${documentTitle} - Summary</title>
        <style>
          body {
            font-family: Arial, sans-serif;
            margin: 40px;
            line-height: 1.6;
            color: #333;
          }
          .header {
            text-align: center;
            border-bottom: 2px solid #333;
            padding-bottom: 20px;
            margin-bottom: 30px;
          }
          .section {
            margin-bottom: 30px;
          }
          .section h2 {
            color: #2c5aa0;
            border-bottom: 1px solid #eee;
            padding-bottom: 10px;
          }
          .summary-content {
            white-space: pre-wrap;
            font-size: 14px;
            background: #f9f9f9;
            padding: 15px;
            border-radius: 5px;
            border-left: 4px solid #2c5aa0;
          }
          .original-content {
            white-space: pre-wrap;
            font-size: 12px;
            background: #f5f5f5;
            padding: 15px;
            border-radius: 5px;
            max-height: 300px;
            overflow-y: auto;
            border-left: 4px solid #ccc;
          }
          .metadata {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 10px;
            margin: 20px 0;
          }
          .metadata-item {
            padding: 10px;
            background: #f0f7ff;
            border-radius: 5px;
          }
          .footer {
            margin-top: 40px;
            text-align: center;
            font-size: 12px;
            color: #666;
            border-top: 1px solid #eee;
            padding-top: 20px;
          }
          @media print {
            body { margin: 20px; }
            .original-content { max-height: none; }
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>Document Summary</h1>
          <h2>${documentTitle}</h2>
          <p>Generated on ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}</p>
        </div>
        
        <div class="section">
          <h2>AI Summary</h2>
          <div class="summary-content">${summaryText}</div>
        </div>
        
        <div class="section">
          <h2>Document Information</h2>
          <div class="metadata">
            <div class="metadata-item">
              <strong>Original Content Length:</strong><br>
              ${originalContent.length} characters
            </div>
            <div class="metadata-item">
              <strong>Summary Length:</strong><br>
              ${summaryText.length} characters
            </div>
            <div class="metadata-item">
              <strong>Compression Ratio:</strong><br>
              ${((summaryText.length / originalContent.length) * 100).toFixed(1)}%
            </div>
            <div class="metadata-item">
              <strong>Words in Original:</strong><br>
              ${originalContent.split(/\s+/).length} words
            </div>
          </div>
        </div>
        
        <div class="section">
          <h2>Original Content Preview</h2>
          <div class="original-content">${originalContent.substring(0, 1000)}${originalContent.length > 1000 ? '...' : ''}</div>
        </div>
        
        <div class="footer">
          <p>Generated by AI Document Summarizer • ${window.location.hostname}</p>
        </div>
      </body>
    </html>
  `;

  printWindow.document.write(htmlContent);
  printWindow.document.close();
  
  // Wait for content to load then print
  setTimeout(() => {
    printWindow.print();
    // Optional: close window after printing
    // printWindow.close();
  }, 250);
};